# Submission of Day-03 assignment From "maheshkamble.official@gmail.com"

In [ ]:
# Q1. Create a numpy array starting from 2 till 50 with a stepsize of 3
#Ans=>

import numpy as np
arr = np.arange(2, 50, 3)
print(arr)

In [ ]:
#Q2. Accept two lists of 5 elements each from the user.Convert them to numpy arrays. 
#    Concatenate these arrays and print it. Also sort these arrays and print it.
# Ans=>

import numpy as np
list1=[]
list2=[]
x=input("Enter 5 elements in list 1separated by space ")
list1=x.split()
x=input("Enter 5 elements in list 2 separated by space ")
list2=x.split()

#typecasting
arr1=np.array(list1)
arr2=np.array(list2)

#concatenating
new_arr=np.sort(np.concatenate((arr1,arr2)))
print(new_arr)

In [26]:
# Q3. Write a code snippet to find the dimensions of a ndarray and its size.
# Ans=>

import numpy as np

my_array= np.array([[1, 4, 7], [3, 6, 9], [1, 4, 7], [3, 6, 9]])
print("Dimensions of a nd array is :", my_array.ndim)

print("Size of an array is :", my_array.size)



Dimensions of a nd array is : 2
Size of an array is : 12


In [28]:
# Q4.How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Ans=>

import numpy as np
arr = np.arange(int(input()))
print(" 1D array (shape)", arr.shape)

two_drow = arr[np.newaxis]
print("2D array for row is", two_drow.shape)

two_dcol = arr[:, np.newaxis]
print(" 2D array for column is", two_dcol.shape)

8
 1D array (shape) (8,)
2D array for row is (1, 8)
 2D array for column is (8, 1)


In [30]:
# Q5.Consider two square numpy arrays. Stack them vertically and horizontally
# Ans=>

import numpy as np

array1 = np.square([1, 4, 5, 8, 9, 6, 3, 5, 2])  
array2 = np.square([4, 5, 8, 6, 9, 7, 4, 5, 6])  


print(np.hstack((array1, array2)))

print(np.vstack((array1, array2)))

[ 1 16 25 64 81 36  9 25  4 16 25 64 36 81 49 16 25 36]
[[ 1 16 25 64 81 36  9 25  4]
 [16 25 64 36 81 49 16 25 36]]


In [34]:
# Q6. How to get unique items and counts of unique items?
# Ans=>

import numpy as np

arr1 = np.array([4, 7, 8, 9, 5, 6, 5, 4, 4])
unique, counts = np.unique(arr1, return_counts=True)
arr1 = np.asarray((unique, counts)).T
print(arr1)

[[4 3]
 [5 2]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
